export const GET_MINIFIGURES = 'GET_MINIFIGURES';
export const GET_MINIFIGURES_SUCCESS = `${GET_MINIFIGURES}/SUCCESS`;
export const GET_MINIFIGURES_ERROR = `${GET_MINIFIGURES}/ERROR`;

export const SET_MINIFIGURES = 'ADD_MINIFIGURE';

export const GET_SETS = 'GET_SETS';
export const SET_SETS = 'ADD_SET';
